name: GitHub Actions CI/CD
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
    
      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test


